DELETE http://localhost:3000/users/6a62c84db84984717350d6e4
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2YTY1NGI0YWM2ZjRkMTJlYWI3MTA2ZTIiLCJ1c2VybmFtZSI6ImFuZ2llLXVzZXIiLCJyb2xlIjoiVXNlciIsImlhdCI6MTc4NTAyNDQ5NywiZXhwIjoxNzg1MTEwODk3fQ.faKoG8YZ4bf_7ByEjpLRKp-GHEYrFFa7Nm2qgdy81gg
