DELETE http://localhost:3000/tasks/6a62cf6696beae6046018c1a
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2YTYyYzg0ZGI4NDk4NDcxNzM1MGQ2ZTQiLCJ1c2VybmFtZSI6ImdpZ2kwMiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc4NDkyNTc2MiwiZXhwIjoxNzg1MDEyMTYyfQ.ijT6NrrlpDSmPi7EHcCQI5g_AxbYjjykN8ufqWhwt14
